AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.12
      CodeUri: src/
      Timeout: 30
      MemorySize: 256
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      BuildMethod: makefile

Outputs:
  FunctionUrl:
    Value: !GetAtt HelloFunctionUrl.FunctionUrl
